apiVersion: v1
kind: PersistentVolume
metadata:
  name: songs-pv
spec:
  capacity:
    storage: 100Mi
  volumeMode: Filesystem
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Recycle
  storageClassName: manual
  hostPath:
    path: /usr/share/nginx/html/songs

---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: songs-pvc
spec:
  storageClassName: manual
  resources:
    requests:
      storage: 100Mi
  accessModes:
    - ReadWriteOnce